# This is a basic workflow to help you get started with Actions

name: Rspec

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache Test Reporter dependency
      id: cache-binary-test-reporter
      uses: actions/cache@v2
      with:
        path: cc-test-reporter
        key: ${{ runner.os }}-binary-test-reporter

    - name: Download the test binary reporter from CodeClimate
      if: steps.cache-binary-test-reporter.outputs.cache-hit != 'true'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Runs a single command using the runners shell
    - name: Bundle Install
      run: |
        gem install bundler:1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Reporter setup
      run: ./cc-test-reporter -d before-build

    # Runs a set of commands using the runners shell
    - name: Run Rspec
      run: COVERAGE=true bundle exec rspec --tag ~redis_cache:true

    - name: Send coverage report
      run: ./cc-test-reporter -d after-build -t simplecov
